---
title: "Intra-rater reliability of LC marking"
author: "Jeremy Elman"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r include=FALSE}
library(psych)
library(dplyr)
library(knitr)

```

# Locus coeruleus contrast-to-noise ratios
```{r, include=FALSE}
home_dir = path.expand("~")
cnrfileConsensus = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_Consensus_All.csv"))
cnrfileKC = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_KC_All.csv"))
cnrfileCP = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_CP_All.csv"))
cnrfileOP = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_OP_All.csv"))
cnrfileRT = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_RT_All.csv"))
cnrfileKE = read.csv(file.path(home_dir,"netshare/VETSA_NAS/PROJ/LC_Marking/results/LC_ROI_KE_All.csv"))

cnrfile_merged = merge(cnrfileConsensus[c("vetsaid","LC_CNR")], cnrfileKC[c("vetsaid","CNR_rostral2")], by="vetsaid", 
                  suffixes = c("_CONS","_KC"))
cnrfile_merged = merge(cnrfile_merged, dplyr::select(cnrfileCP, vetsaid, LC_CNR_CP=CNR_rostral2), by="vetsaid")
cnrfile_merged = merge(cnrfile_merged, dplyr::select(cnrfileOP, vetsaid, LC_CNR_OP=CNR_rostral2), by="vetsaid")
cnrfile_merged = merge(cnrfile_merged, dplyr::select(cnrfileRT, vetsaid, LC_CNR_RT=CNR_rostral2), by="vetsaid")
cnrfile_merged = merge(cnrfile_merged, dplyr::select(cnrfileKE, vetsaid, LC_CNR_KE=CNR_rostral2), by="vetsaid")
```


```{r, echo=FALSE}
kable(cnrfile_merged, digits=3)
```



# Intraclass Correllation Coefficients 


```{r, cho=FALSE}
ICC(dplyr::select(cnrfile_merged, -vetsaid))
```


